"""empty message

Revision ID: 1d79d65abe6f
Revises: None
Create Date: 2014-07-12 12:27:44.853749

"""

# revision identifiers, used by Alembic.
revision = '1d79d65abe6f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('wid', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=50), nullable=True),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('wid'),
    sa.UniqueConstraint('word')
    )
    op.create_table('prohibited_words',
    sa.Column('pwid', sa.Integer(), nullable=False),
    sa.Column('wid', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=50), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wid'], ['words.wid'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('pwid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prohibited_words')
    op.drop_table('words')
    ### end Alembic commands ###
