"""empty message

Revision ID: 2b576574e73b
Revises: 4de09f99b8b5
Create Date: 2014-07-16 23:52:48.682981

"""

# revision identifiers, used by Alembic.
revision = '2b576574e73b'
down_revision = '4de09f99b8b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'verified')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('verified', sa.BOOLEAN(), nullable=False))
    ### end Alembic commands ###
