"""empty message

Revision ID: 4de09f99b8b5
Revises: 1d79d65abe6f
Create Date: 2014-07-16 22:26:52.637416

"""

# revision identifiers, used by Alembic.
revision = '4de09f99b8b5'
down_revision = '1d79d65abe6f'

from alembic import op
import sqlalchemy as sa
import alembic

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    context = op.get_context()
    if context.bind.dialect.name == 'postgresql':
        has_size_type = context.bind.execute( \
                "select exists (select 1 from pg_type " \
                "where typname='word_status')").scalar()
        if not has_size_type:
            op.execute("CREATE TYPE word_status AS ENUM ('unverified', 'approved', 'rejected')")
    op.add_column('words', sa.Column('status', sa.Enum('unverified', 'approved', 'rejected', name='word_status'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'status')
    context = op.get_context()
    if context.bind.dialect.name == 'postgresql':
        has_size_type = context.bind.execute( \
                "select exists (select 1 from pg_type " \
                "where typname='word_status')").scalar()
        if has_size_type:
            op.execute("DROP TYPE word_status")
    ### end Alembic commands ###
